language: perl
perl:
  - "5.16"
services:
  - rabbitmq
before_install:
  - export TRAVIS_BUILD_DIR="$TRAVIS_BUILD_DIR/src/perl/"
  - cd $TRAVIS_BUILD_DIR
install:
  - perl Build.PL
  - yes | perl Build installdeps

script: "cd $TRAVIS_BUILD_DIR && perl Build && perl Build test"
